# Generated by Django 5.1.4 on 2025-01-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("temperature", models.FloatField()),
                ("description", models.CharField(max_length=255)),
                ("date_fetched", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
