# Generated by Django 5.1.4 on 2025-01-17 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_city_forecast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.city"
            ),
        ),
    ]
